/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import twitter from "../../public/icon/twitter.svg";
import linkedin from "../../public/icon/linkedin.svg";
import facebook from "../../public/icon/facebook.svg";
import aboutme from "../../public/aboutme.jpg";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="no-scrollbar h-screen min-w-[800px] overflow-y-scroll bg-[url('../../public/background.jpg')] bg-cover">
        {/* //!Header */}
        <div className=" fixed left-0 top-0 z-[100] flex w-full items-center justify-between px-[9%] py-[2rem] mix-blend-difference">
          <a
            className=" cursor-default text-[2rem] font-semibold text-[--text-color] transition-all lg:text-[3rem]"
            href="#"
          >
            Boom.
          </a>
          {/* <div className=" text-[3.6rem]">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              />
            </svg>
          </div> */}
          <nav className=" bg-transparent text-[1.25rem] font-semibold text-[--text-color] ">
            <a
              href="#home"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
            >
              Home
            </a>
            <a
              href="#about"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
            >
              About
            </a>
            <a
              href="#education"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
            >
              Education
            </a>
            <a
              href="#skill"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
            >
              Skill
            </a>
            <a
              href="#contact"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
            >
              Contact
            </a>
          </nav>
        </div>

        {/* //! home section */}
        <section className="flex min-h-full flex-col px-[9%] pb-[2rem] pt-[10rem] text-white">
          <div className="py-auto flex max-w-[60rem] grow flex-col justify-center gap-5 px-[9%]">
            <h1 className=" text-[5rem] font-bold ">
              Hi, I&apos;m <span>Phurinat Wongkasetchai</span>
            </h1>
            <div className=" text-stroke relative text-[3.2rem] font-bold">
              <h3>Frontend Developer</h3>
            </div>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Inventore quisquam recusandae nam a, nobis rerum quidem voluptas
              eligendi architecto perspiciatis, similique quo aliquid, id
              consectetur natus iste tenetur delectus maxime?
            </p>

            <div className="flex gap-5">
              <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
                <a
                  href="#"
                  className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
                >
                  <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                    Hire me
                  </p>
                </a>
              </div>
              <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
                <a
                  href="#"
                  className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
                >
                  <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                    Let&apos;s talk
                  </p>
                </a>
              </div>
            </div>
          </div>

          <div className="flex h-[8rem] gap-5 pt-[3rem]">
            <a
              href="#"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={twitter} alt="" />
            </a>
            <a
              href="#"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={linkedin} alt="" />
            </a>
            <a
              href="#"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={facebook} alt="" />
            </a>
          </div>
        </section>

        {/* //!about section */}
        <section className=" flex min-h-full flex-col items-center justify-center gap-[2rem] bg-[--bg-color] px-[5rem] text-white">
          <h2 className="mt-[5rem] flex text-center text-[3rem] font-semibold">
            About <span className="text-[--main-color]">Me</span>
          </h2>
          <div className=" relative flex h-[25rem] w-[25rem] items-center justify-center   ">
            <div className=" z-[2] flex h-[90%] w-[90%] items-center justify-center overflow-hidden rounded-[50%] border-[.2rem] border-[--main-color]">
              <Image
                src={aboutme}
                alt=""
                className="  bg-cover transition-all duration-300 hover:scale-105 "
              />
            </div>
            <span className="absolute left-[50%] top-[50%] z-[1] h-full w-full translate-x-[-50%] translate-y-[-50%] rotate-0 rounded-[50%] border-b-[.2rem] border-l-[.2rem] border-r-[.2rem] border-t-[.2rem] border-b-[--bg-color] border-l-[--main-color] border-r-[--main-color] border-t-[--bg-color]"></span>
          </div>

          <div className=" flex flex-col items-center text-center">
            <h3 className=" text-[2rem] font-semibold">Frontend Developer!</h3>
            <p className=" mb-[3rem] mt-[2rem] text-[1.2rem]">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error
              ipsum animi reiciendis veritatis id doloremque suscipit labore
              expedita! Natus quis magni voluptatem vel ad laborum quas
              repellendus iure id eligendi voluptates, esse quibusdam placeat
              omnis cupiditate reiciendis error nobis itaque, saepe dolorum?
              Unde similique ad dolorum beatae dolore, laborum eveniet repellat
              laboriosam libero accusantium animi voluptas cumque. Blanditiis
              sit aut quaerat vero consequuntur quisquam saepe laboriosam
              corporis, minus iure, recusandae architecto labore accusamus
              delectus ipsam!
            </p>

            <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
              <a
                href="#"
                className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
              >
                <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                  Read More
                </p>
              </a>
            </div>
          </div>
        </section>

        {/* //!education section */}
        {/* <section className=" min-h-full bg-[--bg-color] px-[5rem] text-white"></section> */}
      </main>
    </>
  );
};

export default Home;
