/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import twitter from "../../public/icon/twitter.svg";
import linkedin from "../../public/icon/linkedin.svg";
import facebook from "../../public/icon/facebook.svg";
import aboutme from "../../public/aboutme.jpg";
import arrow_up from "../../public/icon/arrow_up.svg";
// import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // useEffect(() => {
  //   const allsections = document.querySelectorAll("section");
  //   allsections.forEach((sec) => {
  //     sec.classList.remove("section-aimation");
  //   });
  // }, []);

  // const clicksection = (id: string) => {
  //   const sections = document.getElementById(id);

  //   sections.classList.add("section-aimation");
  // };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="no-scrollbar h-screen min-w-[800px] overflow-y-scroll scroll-smooth bg-[url('../../public/background.jpg')] bg-cover">
        {/* //!Header */}
        <div className=" fixed left-0 top-0 z-[100] flex w-full items-center justify-between px-[9%] py-[2rem] mix-blend-difference">
          <a
            className=" relative cursor-default text-[2rem] font-semibold text-[--text-color] transition-all lg:text-[3rem]"
            href="#"
          >
            Boom.<span className="onreload"></span>
          </a>
          {/* <div className=" text-[3.6rem]">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              />
            </svg>
          </div> */}
          <nav className=" relative bg-transparent text-[1.25rem] font-semibold text-[--text-color] ">
            <a
              href="#home"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
              // onClick={() => clicksection("home")}
            >
              Home
            </a>
            <a
              href="#about"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
              // onClick={() => clicksection("about")}
            >
              About
            </a>
            <a
              href="#education"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
              // onClick={() => clicksection("education")}
            >
              Education
            </a>
            <a
              href="#skill"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
              // onClick={() => clicksection("skill")}
            >
              Skill
            </a>
            <a
              href="#contact"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all  duration-300 hover:bg-white hover:text-black active:bg-[#2c7a6c] active:text-white"
              // onClick={() => clicksection("contact")}
            >
              Contact
            </a>
            <span className="onreload"></span>
          </nav>
        </div>

        {/* //! home section */}
        <section
          className="flex min-h-full flex-col px-[9%] pb-[2rem] pt-[10rem] text-white"
          id="home"
        >
          <div className="py-auto flex max-w-[60rem] grow flex-col justify-center gap-5 px-[9%]">
            <h1 className=" text-[5rem] font-bold ">
              Hi, I&apos;m <span>Phurinat Wongkasetchai</span>
            </h1>
            <div className="relative w-fit">
              <h3 className="text-stroke anin text-animationbg relative text-clip bg-gradient-to-r from-[--main-color] to-[--main-color] bg-no-repeat text-[3.2rem] font-bold ">
                Frontend Developer
              </h3>
              <div className="text-animationcs absolute left-0 top-0 h-full w-0 border-r-[3px] border-[--main-color]"></div>
            </div>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Inventore quisquam recusandae nam a, nobis rerum quidem voluptas
              eligendi architecto perspiciatis, similique quo aliquid, id
              consectetur natus iste tenetur delectus maxime?
            </p>

            <div className="flex gap-5">
              <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
                <a
                  href="#"
                  className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
                >
                  <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                    Hire me
                  </p>
                </a>
              </div>
              <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
                <a
                  href="#"
                  className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
                >
                  <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                    Let&apos;s talk
                  </p>
                </a>
              </div>
            </div>
          </div>

          <div className="flex h-[8rem] gap-5 pt-[3rem]">
            <a
              href="#"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={twitter} alt="" />
            </a>
            <a
              href="https://www.linkedin.com/in/phurinat/"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={linkedin} alt="" />
            </a>
            <a
              href="#"
              className=" relative inline-flex h-[50px] w-[50px] items-center justify-center rounded-[50%] border-[.2rem] border-[--main-color] bg-transparent transition-all duration-500 hover:bg-[--second-bg-color]"
            >
              <Image src={facebook} alt="" />
            </a>
          </div>
          <span className="section-animation"></span>
        </section>

        {/* //!about section */}
        <section
          className=" flex min-h-full flex-col items-center justify-center gap-[2rem] bg-[--second-bg-color] px-[5rem] text-white"
          id="about"
        >
          <h2 className="mt-[5rem] flex text-center text-[3rem] font-semibold">
            About <span className="text-[--main-color]">Me</span>
          </h2>
          <div className=" relative flex h-[25rem] w-[25rem] items-center justify-center   ">
            <div className=" z-[2] flex h-[90%] w-[90%] items-center justify-center overflow-hidden rounded-[50%] border-[.2rem] border-[--main-color]">
              <Image
                src={aboutme}
                alt=""
                className="  bg-cover transition-all duration-300 hover:scale-105 "
              />
            </div>
            <span className="circle-spin absolute left-[50%] top-[50%] z-[1] h-full w-full translate-x-[-50%] translate-y-[-50%] rotate-0 rounded-[50%] border-b-[.2rem] border-l-[.2rem] border-r-[.2rem] border-t-[.2rem] border-b-[--second-bg-color] border-l-[--main-color] border-r-[--main-color] border-t-[--second-bg-color]"></span>
          </div>

          <div className=" flex flex-col items-center text-center">
            <h3 className=" text-[2rem] font-semibold">Frontend Developer!</h3>
            <p className=" mb-[3rem] mt-[2rem] text-[1.2rem]">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Error
              ipsum animi reiciendis veritatis id doloremque suscipit labore
              expedita! Natus quis magni voluptatem vel ad laborum quas
              repellendus iure id eligendi voluptates, esse quibusdam placeat
              omnis cupiditate reiciendis error nobis itaque, saepe dolorum?
              Unde similique ad dolorum beatae dolore, laborum eveniet repellat
              laboriosam libero accusantium animi voluptas cumque. Blanditiis
              sit aut quaerat vero consequuntur quisquam saepe laboriosam
              corporis, minus iure, recusandae architecto labore accusamus
              delectus ipsam!
            </p>

            <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
              <a
                href="#"
                className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
              >
                <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                  Read More
                </p>
              </a>
            </div>
          </div>
          <span className="section-animation"></span>
        </section>

        {/* //!education section */}
        <section
          className="flex min-h-full flex-col items-center justify-center bg-[--bg-color] px-[5rem] text-white"
          id="education"
        >
          <h2 className="my-[2rem] flex text-center text-[3rem] font-semibold">
            My <span className="text-[--main-color]">Journey</span>
          </h2>

          <div className="flex flex-wrap gap-[5rem]">
            <div className="flex-[1_1_40rem]">
              <h3 className="mb-[1.5rem] ml-[2rem] text-[2.5rem]">Education</h3>
              <div className="border-l-[.2rem] border-[--main-color]">
                <div className="  relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className=" pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2017 - 2018
                    </div>
                    <h3 className=" text-[1.5rem]">
                      Master Degree - University
                    </h3>
                    <p className=" pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>

                <div className=" relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className="pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2019 - 2020
                    </div>
                    <h3 className="text-[1.5rem]">
                      Master Degree - University
                    </h3>
                    <p className="pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>

                <div className="  relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className="pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2021 - 2022
                    </div>
                    <h3 className="text-[1.5rem]">
                      Master Degree - University
                    </h3>
                    <p className="pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex-[1_1_40rem]">
              <h3 className="mb-[1.5rem] ml-[2rem] text-[2.5rem]">
                Experience
              </h3>
              <div className="border-l-[.2rem] border-[--main-color]">
                <div className="  relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className="pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2017 - 2018
                    </div>
                    <h3 className="text-[1.5rem]">Web Deverloper - Company</h3>
                    <p className="pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>

                <div className="  relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className="pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2019 - 2020
                    </div>
                    <h3 className="text-[1.5rem]">Web Deverloper - Company</h3>
                    <p className="pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>

                <div className="  relative pl-[2rem] before:absolute before:left-[-1.1rem] before:top-0 before:h-[2rem] before:w-[2rem] before:rounded-[50%] before:bg-[--main-color] before:transition-all before:duration-500 hover:before:translate-y-[570%]">
                  <div className="relative z-0 mb-[2rem] overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] p-[1.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-full">
                    <div className="pb-[.5rem] text-[1.5rem] text-[--main-color]">
                      2021 - 2022
                    </div>
                    <h3 className="text-[1.5rem]">Web Deverloper - Company</h3>
                    <p className="pt-[.5rem]">
                      Lorem ipsum, dolor sit amet consectetur adipisicing elit.
                      Blanditiis incidunt, accusamus delectus odio repudiandae
                      beatae, laborum numquam porro dolorem voluptatum velit
                      optio earum omnis dignissimos harum voluptates
                      consequuntur molestias hic?
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <span className="section-animation"></span>
        </section>

        {/* //!skill section */}
        <section
          className="flex min-h-full flex-col items-center justify-center bg-[--second-bg-color] px-[5rem] text-white"
          id="skill"
        >
          <h2 className="my-[2rem] flex text-center text-[3rem] font-semibold">
            My <span className="text-[--main-color]">Skills</span>
          </h2>

          <div className=" flex-warp flex w-full gap-[5rem]">
            <div className="flex-[1_1_40rem]">
              <h3 className=" mb-[1.5rem] text-[2rem]">Coding Skills</h3>

              <div className=" relative z-0 overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] px-[1.5rem] py-[.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--bg-color] before:transition-all before:duration-500 hover:before:w-full">
                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    HTML <span className=" font-semibold">90%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[90%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    CSS <span className=" font-semibold">95%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[95%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    JAVA <span className=" font-semibold">80%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[80%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    Typescript <span className=" font-semibold">68%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[68%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>
              </div>
            </div>

            <div className="flex-[1_1_40rem]">
              <h3 className=" mb-[1.5rem] text-[2rem]">Profressional Skills</h3>

              <div className=" relative z-0 overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] px-[1.5rem] py-[.5rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--bg-color] before:transition-all before:duration-500 hover:before:w-full">
                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    CEO <span className=" font-semibold">99%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[99%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    Web Design <span className=" font-semibold">90%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[90%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    Web Development <span className=" font-semibold">90%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[90%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>

                <div className="py-[1rem]">
                  <h3 className=" flex justify-between text-[1.3rem]">
                    CFO <span className=" font-semibold">80%</span>
                  </h3>
                  <div className="my-[1rem] h-[2.5rem] rounded-[.6rem] border-[.2rem] border-[--main-color] p-[.5rem] ">
                    <span className="block h-full w-[80%] rounded-[.3rem] bg-[--main-color]"></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <span className="section-animation"></span>
        </section>

        {/* //!contact section */}
        <section
          className="flex min-h-full flex-col items-center justify-center bg-[--bg-color] px-[5rem] text-white"
          id="contact"
        >
          <h2 className="my-[2rem] flex text-center text-[3rem] font-semibold">
            <span className="text-[--main-color]">Contact</span> Me!
          </h2>

          <form className=" gap- mx-auto flex w-full max-w-[70rem] flex-col text-center">
            <div className=" flex-warp relative my-[.8rem] flex h-[83px] justify-between">
              <div className=" relative h-full w-[49%] overflow-hidden rounded-[.6rem]">
                <input
                  placeholder="Full Name"
                  required
                  type="text"
                  className=" peer absolute left-0 h-full w-full rounded-[.6rem] border-[.2rem] border-[--main-color] bg-transparent p-[1.5rem] text-[1.6rem] text-[--text-color] outline-none placeholder:text-[--text-color]"
                ></input>
                <div className=" left-0 top-0 h-full w-0 rounded-[.6rem] bg-[--second-bg-color] transition-all duration-500 peer-valid:w-full peer-focus:w-full"></div>
              </div>
              <div className=" relative h-full w-[49%] overflow-hidden rounded-[.6rem]">
                <input
                  placeholder="Email Address"
                  required
                  type="text"
                  className=" peer absolute left-0 h-full w-full rounded-[.6rem] border-[.2rem] border-[--main-color] bg-transparent p-[1.5rem] text-[1.6rem] text-[--text-color] outline-none placeholder:text-[--text-color]"
                ></input>
                <div className="left-0 top-0 h-full w-0 rounded-[.6rem] bg-[--second-bg-color] transition-all duration-500 peer-valid:w-full peer-focus:w-full"></div>
              </div>
            </div>

            <div className=" flex-warp relative my-[.8rem] flex h-[83px] justify-between">
              <div className=" relative  h-full w-[49%] overflow-hidden rounded-[.6rem]">
                <input
                  placeholder="Mobile Number"
                  required
                  type="number"
                  className="peer absolute left-0 h-full w-full rounded-[.6rem] border-[.2rem] border-[--main-color] bg-transparent p-[1.5rem] text-[1.6rem] text-[--text-color] outline-none placeholder:text-[--text-color]"
                ></input>
                <div className=" left-0 top-0 h-full w-0 rounded-[.6rem] bg-[--second-bg-color] transition-all duration-500 peer-valid:w-full peer-focus:w-full"></div>
              </div>
              <div className=" relative h-full w-[49%] overflow-hidden rounded-[.6rem]">
                <input
                  placeholder="Email Subject"
                  required
                  type="text"
                  className=" peer absolute left-0 h-full w-full rounded-[.6rem] border-[.2rem] border-[--main-color] bg-transparent p-[1.5rem] text-[1.6rem] text-[--text-color] outline-none placeholder:text-[--text-color]"
                ></input>
                <div className=" left-0 top-0 h-full w-0 rounded-[.6rem] bg-[--second-bg-color] transition-all duration-500 peer-valid:w-full peer-focus:w-full"></div>
              </div>
            </div>

            <div className=" relative mb-[2.7rem] mt-[.8rem] flex h-[438px] justify-between overflow-hidden rounded-[.6rem]">
              <textarea
                name=""
                id=""
                cols={30}
                rows={10}
                placeholder="Your Message"
                required
                className=" peer absolute left-0 h-full w-full resize-none rounded-[.6rem] border-[.2rem] border-[--main-color] bg-transparent p-[1.5rem] text-[1.6rem] text-[--text-color] outline-none placeholder:text-[--text-color]"
              ></textarea>
              <div className=" left-0 top-0 h-full w-0 rounded-[.6rem] bg-[--second-bg-color] transition-all duration-500 peer-valid:w-full peer-focus:w-full"></div>
            </div>

            <div className="flex justify-center">
              <div className=" z-1 relative flex h-[5rem] overflow-hidden rounded-[.8rem]">
                <a
                  href="#home"
                  className=" z-0 overflow-hidden rounded-[.8rem] bg-[--main-color] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:rounded-[.8rem] before:bg-[--second-bg-color] before:transition-all before:duration-500 hover:before:w-[15rem]"
                >
                  <p className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem] border-[--main-color] text-[1.8rem] font-semibold text-[--bg-color] transition-all duration-500 hover:text-[--main-color]">
                    Submit
                  </p>
                </a>
              </div>
            </div>
          </form>
          <span className="section-animation"></span>
        </section>

        {/* //!footer */}
        <footer className="flex flex-wrap items-center justify-between bg-[--second-bg-color] px-[9%] py-[2rem] text-white">
          <div>
            <p className="text-[1.3rem]">
              Copyright &copy; 2023 by BoomCTR (phurinat wongkasetchai) | All
              Rights Reserved.
            </p>
          </div>

          <div>
            <a
              href="#home"
              className="peer relative z-0 inline-flex items-center justify-center overflow-hidden rounded-[.6rem] border-[.2rem] border-[--main-color] bg-[--main-color] p-[.8rem] before:absolute before:left-0 before:top-0 before:z-[-1] before:h-full before:w-0 before:bg-[--bg-color] before:transition-all before:duration-500 hover:before:w-full"
            >
              <img
                src={arrow_up["src"]}
                width={arrow_up["width"]}
                height={arrow_up["height"]}
              />
            </a>
          </div>
        </footer>
      </main>
    </>
  );
};

export default Home;
