import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-[--bg-color] text-white">
        {/* //!Header */}
        <div className=" fixed left-0 top-0 z-[100] flex w-full items-center justify-between px-[9%] py-[2rem]">
          <a
            className=" cursor-default text-[3rem] font-semibold text-[--text-color]"
            href="#"
          >
            Boom.
          </a>
          {/* <div className=" text-[3.6rem]">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              width="16"
              height="16"
              fill="currentColor"
              viewBox="0 0 16 16"
            >
              <path
                fill-rule="evenodd"
                d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"
              />
            </svg>
          </div> */}
          <nav className=" bg-transparent text-[1.25rem] font-semibold text-[#359381]">
            <a
              href="#home"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all hover:bg-[#359381] hover:text-white active:bg-[#2c7a6c] active:text-white"
            >
              Home
            </a>
            <a
              href="#about"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all hover:bg-[#359381] hover:text-white active:bg-[#2c7a6c] active:text-white"
            >
              About
            </a>
            <a
              href="#education"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all hover:bg-[#359381] hover:text-white active:bg-[#2c7a6c] active:text-white"
            >
              Education
            </a>
            <a
              href="#skill"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all hover:bg-[#359381] hover:text-white active:bg-[#2c7a6c] active:text-white"
            >
              Skill
            </a>
            <a
              href="#contact"
              className="mx-[10px] rounded-[20px] px-[15px] py-[6px] transition-all hover:bg-[#359381] hover:text-white active:bg-[#2c7a6c] active:text-white"
            >
              Contact
            </a>
          </nav>
        </div>

        {/* //! home section */}
        <section className="flex min-h-full items-center px-[9%] pb-[2rem] pt-[10rem] ">
          <div className="flex max-w-[60rem] flex-col gap-5 px-[9%]">
            <h1 className=" text-[5rem] font-bold ">
              Hi, I&apos;m <span>Phurinat Wongkasetchai</span>
            </h1>
            <div className=" text-stroke relative text-[3.2rem] font-bold">
              <h3>Frontend Developer</h3>
            </div>
            <p>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit.
              Inventore quisquam recusandae nam a, nobis rerum quidem voluptas
              eligendi architecto perspiciatis, similique quo aliquid, id
              consectetur natus iste tenetur delectus maxime?
            </p>

            <div className=" relative flex h-[5rem] w-[34.5rem] justify-between">
              <a
                href="#"
                className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem_solid_--main-color] bg-[--main-color] text-[1.8rem] font-semibold text-[--bg-color]"
              >
                Hire me
              </a>
              <a
                href="#"
                className=" inline-flex h-full w-[15rem] items-center justify-center rounded-[.8rem] border-[.2rem_solid_--main-color] bg-[--main-color] text-[1.8rem] font-semibold text-[--bg-color]"
              >
                Let&apos;s talk
              </a>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default Home;
